### ISSUE TITLE
NCBI switching exclusively to https as of 9/26/2016

### ISSUE THREAD

**Issue by nthmost** [biocommons/eutils#137]
See https://www.ncbi.nlm.nih.gov/home/bulletins/https-tests.shtml

It's possible nothing in eutils will break because of this, since they are forwarding HTTP to HTTPS, but it's worth updating the code to reflect https universally since there's no guarantee they will continue to support HTTP at all.  Which is a good thing.  :)

**Comment by reece** [comment]
So true... and it's already fixed!

https://github.com/biocommons/eutils/issues/136

Happy belated birthday, btw.  :smile:

**Comment by nthmost** [comment]
Oops!!  Sorry for opening a dup ticket, then.  Thanks on all counts! :)
