### ISSUE TITLE
 QueryService treats all error responses from NCBI as being encoded as XML

### ISSUE THREAD

**Issue by diekhans** [biocommons/eutils#142]
QueryService treats all error responses from NCBI as being encoded as XML.  For instance,
setting db="" in fetch results in response text of:

`Bad Request (400): Mandatory parameter: db - is omitted`

The raise of EutilsNCBIError also loses the parse error message, so it's a mystery why the request failed.    I will be submitting a pull request that fixes the raise and leave it to those who better understand the NCBI behavior to

**Comment by reece** [comment]
Merged long ago. Dunno why it wasn't closed.
