### ISSUE TITLE
A bug in the abstract property in medlinecitation.py

### ISSUE THREAD

**Issue by jinseonyou** [biocommons/eutils#149]
Hello.
I have been deeply impressed by the convenience provided by eutils package and appreciate your contribution!
In the meantime, I may find a bug in medlinecitation.py:
`        return self._xml_root.findtext('Article/Abstract/AbstractText')`
(https://github.com/biocommons/eutils/blob/master/eutils/xmlfacades/medlinecitation.py#L15)

The code not seems to extract full text of an abstract in the case where there are multi AbstractText elements, (e.g. 22351513[pmid]).
I think if you modify the code below, it probably works well:
`        return '\n'.join([at.text for at in self._xml_root.findall('Article/Abstract/AbstractText')])`

**Comment by reece** [comment]
Thanks for the bug report @jinseonyou! 0.3.1 is now available in pypi.
