### ISSUE TITLE
option to specify API key for QueryService instances

### ISSUE THREAD

**Issue by pmartin23** [biocommons/eutils#152]
[Looks like](https://www.ncbi.nlm.nih.gov/books/NBK25497/#_chapter2_Usage_Guidelines_and_Requiremen_) NCBI will be throttling users without an API key to 3 requests/s from 1st May 2018, and allowing up to 10 requests/s for users who provide an API key. Would be great to be able to provide the key to the QueryService object in order to automatically include the key in all queries, similarly to the 'email' and 'tool' params.

**Comment by reece** [comment]
I agree that this would be useful... and easy to implement. PRs welcome.

API keys are created at https://www.ncbi.nlm.nih.gov/account/settings/.

**Comment by reece** [comment]
Related: biocommons/bioutils#10

**Comment by reece** [comment]
@pmartin23 @timothyjlaurent 
Support for api keys was just released in eutils 0.4.0. See https://eutils.readthedocs.io/en/stable/changelog/0.4.html.

Thanks @timothyjlaurent for the PR that kicked this off.
