### ISSUE TITLE
Edge case results in error being thrown when extracting abstract text in medlinecitation.py

### ISSUE THREAD

**Issue by pmartin23** [biocommons/eutils#157]
Hey there,

Firstly - this library has saved me so much time. Thanks for all of your hard work!

Today I noticed I was receiving an error when trying to access the abstract property of this specific [PubMed article](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=29915538&retmode=xml) and upon further investigation saw that (unusually) the AbstractText contains formatting tags which seems to break line 16 in medlinecitation.py:
    `return " ".join([at.text for at in self._xml_root.findall('Article/Abstract/AbstractText')])`

The issue seems to be fixed by changing the line to the below, which should capture the text of all AbstractText and child elements: 
`return " ".join(["".join(at.itertext()) for at in self._xml_root.findall('Article/Abstract/AbstractText')])`

I'm new to open source contribution but would love to make this my first PR!

**Comment by reece** [comment]
Hi @pmartin23 - So sorry for the long delay. I completely missed this comment in eutils. I'm glad the library is useful to you!

I agree with your diagnosis and solution. It would be great to have a PR from you. Please let me know if you need any help in preparing a PR -- see my profile for my email address.
