### ISSUE TITLE
modernize eutils development practice

### ISSUE THREAD

**Issue by reece** [biocommons/eutils#161]
For this issue, modernize eutils with pipenv and other changes as appropriate. The goal use and stay current with modern development practices to ease developer burden. 

For example, pipenv appears to be gaining traction by the community and supplants many of the home-grown ways of managing environments in biocommons tools (e.g., the heinous Makefile).

Because eutils is mostly independent of other biocommons projects, it makes a good guinea pig for testing modernization.

Consider:
* pipenv
* [Bandit](https://pypi.org/project/bandit/)
* linters
* static checkers
* code reformatters
* pytest w/fixtures (we're part way there)
* pydoctest
* isort

**Comment by reece** [comment]
Also see https://deepsource.io/gh/jaipradeesh/hgvs/issues/.

**Comment by jaipradeesh** [comment]
https://deepsource.io/gh/jaipradeesh/eutils/issues/

**Comment by reece** [comment]
pipenv looks less attractive than reports initially suggested.
Implemented deepsource and yapf.
That's enough for now. Closing.
