### ISSUE TITLE
Address issues found by Deepsource

### ISSUE THREAD

**Issue by reece** [biocommons/eutils#167]
Triage issues at https://deepsource.io/gh/biocommons/eutils/ and create a plan for resolving them. Options are:
* Easy -- solve now.
* Harder -- defer, perhaps creating an issue for them.
* Ignore -- Not a serious issue.

**Comment by richardNam** [comment]
Hi @reece I can take a look at the second issue `Undefined name detected`. Anything I should be aware of before I dive in?

**Comment by reece** [comment]
I don't think there are any surprises here. Go for it!
Please get in touch if you need help.
Thanks for diving in, @richardNam!

**Comment by reece** [comment]
Comments:
* pubmedcentralarticle.py: This couldn't be working. It's likely a copy-paste error. This also means that we need a test here. :-(
* entrezgene.py: Also couldn't be working. There's supposed to be a class `EntrezgeneLocus`, but it's not imported... and, worse, it doesn't even exist apparently. 
* einforesult.py: Probably just needs an import in both cases.
